### PR TITLE
fix mlopen assert

### PR DESCRIPTION
**Pull request by dfukalov**
1. removed processing GVs that are not used in current kernel to fix assertion in next kenrnels cloning
2. minor strings related optimizations

### CODE REVIEW

**Comment by whchung** [comment]
@dfukalov I can't see new codes in `updateBitCastInstWithNewOperand()` ?

**Comment by dfukalov** [comment]
It seems I did it in different branch. But this branch fixed mlopen and I checked it with "hcc/build/make test" so I suggest to use this smaller change

**Comment by whchung** [comment]
I can take this. Would you submit another pull request for changes in `updateBitCastInstWithNewOperand`?

**Comment by dfukalov** [comment]
I actually have no test to check that CreatePointerBitCastOrAddrSpaceCast is needed, so I would keep it in current state

**Comment by whchung** [comment]
@dfukalov does it mean mlopen assert issue is gone simply by merging this pull request?

**Comment by dfukalov** [comment]
yes, mlopen now builds ok and opt works now less than minute in linking part
works correctly on a number of configurations I checked

**Pull request merged**
