### PR TITLE
[HCC] Translate register control attributes in WrapperGen for grid la…

### PR DESCRIPTION
**Pull request by yxsamliu**
…unchinging.

### CODE REVIEW

**Comment by scchan** [comment]
LGTM, looks like this patch also supports the grid_launch mode?
Could you also add a few unit tests for this feature to hcc?  Thanks!

**Comment by bensander** [comment]
We should take a (brief) quick look but my recollection is GL stripped the attributes, somehow.  GGL should fix.
-ben

**Comment by yxsamliu** [comment]
I have a pull request to add unit tests to hcc for PEF and GridLaunch with register control.
https://github.com/RadeonOpenCompute/hcc/pull/238

**Comment by scchan** [comment]
@bensander  It looks like Sam's patch has some logic to re-emit the register control attributes when hcc translates a GL kernel into a PFE so the register control attributes would be preserved.

@yxsamliu can you confirm?

**Review by whchung — APPROVED** [review]
LGTM

**Comment by yxsamliu** [comment]
@scchan @bensander Basically, Clang emit register control attr in llvm for GL kernel, then in this wrapper those llvm attributes are re-emitted to C++ source code for PFE, then clang translates them again in llvm for the trampoline functions. So the final kernel will have the register control attributes.

**Comment by bensander** [comment]
Nice !  Sounds like a solid improvement.  Might help with other issue we have seen where attributes (static, etc) are lost or manipulated on the path to GL as well.

**Pull request merged**
