### PR TITLE
Tweak SelectAcceleratorCode

### PR DESCRIPTION
**Pull request by AlexVlx**
This slightly changes SelectAcceleratorCode to make it more legible, 
slightly more reliable and slightly faster. The reliability comes from
moving the procedure for annotating functions in the HC reachable set
with 'always_inline' into runOnModule from doFinalization. This is
because the latter offers no guarantees beyond that it will run last,
thus making it possible for other passes to be interposed and possibly
fail. The speed increase comes by way of observing that the only viable
root nodes for the HC reachable set are the kernels i.e. functions which
have teh AMDGPU_KERNEL calling convention. Obtaining the function name
is less convoluted as well.

### CODE REVIEW

**Comment by yxsamliu** [comment]
LGTM.

I think in the future we should follow LLVM coding style in clang/llvm code, e.g. by  using capitalized variable names. Otherwise we will get trouble upstreaming them.

**Comment by AlexVlx** [comment]
@yxsamliu thank you for the comments. I've tried to update the PR accordingly, if you'd care to take a look. In general I'd like to strive for closeness to Clang / LLVM style as much as possible so that we can try to upstream sooner as opposed to later, so that observation was more than welcome.

**Review by yxsamliu — COMMENTED** [review]
LGTM. Thanks.

**Review by whchung — APPROVED** [review]
LGTM. Would it be possible to make it an AMDGPU-specific opt pass by putting it under `lib/Target/AMDGPU`?

**Comment by yxsamliu** [comment]
I think it is fine to add it to lib/Target/AMDGPU.

**Pull request merged**
