### PR TITLE
Merge with trunk about alloca. Lower frame index as 32 bit

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by whchung** [comment]
@yxsamliu since this PR is so vast, could you let me know to which git commit # in `amd-common` branch would it be synced with?

**Comment by yxsamliu** [comment]
These should be in synch with ca101a16bfc8ee48fa20994c11ec32bbfc525457, but they should be able to synch up to tip since I don't think there are conflicting commits up to tip. If there are upcoming conflicting commits I will add them here.

**Comment by whchung** [comment]
@yxsamliu same as https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/35 , this PR will be held until known regressions in HCC unit tests are resolved

**Comment by whchung** [comment]
This PR is temporarily store under branch `amd-hcc-alloca`. It would be merged back to `amd-hcc` once remaining failing HCC unit tests are resolved.

**Pull request merged**
