### PR TITLE
Remove non-temporal flag for kernargs

### PR DESCRIPTION
**Pull request by whchung**
This help removes SLC / GLC bits when loading from sub-dword kernel arguments, which is very important for performance.

### CODE REVIEW

**Comment by sunway513** [comment]
This PR has been verified with the last HCC release branch, and proved to be able to boost the performance on DL workloads significantly.

**Review by sunway513 — APPROVED** [review]
LGTM

**Comment by scchan** [comment]
@whchung could you change this PR to make it land on amd-hcc first?  The cherry-picking of this into 1.7 has to be done gerrit.

**Comment by whchung** [comment]
@scchan thx. it's done

**Comment by scchan** [comment]
@whchung several other unrelated commits got picked up, I think you'll have to do this from a fresh amd-hcc branch

**Comment by whchung** [comment]
cleaned commit history and re-filed #134

**Pull request closed without merging**
