### PR TITLE
Removed dead store into addr space casted alloca

### PR DESCRIPTION
**Pull request by yxsamliu**
Change-Id: Ia2234ea9ab31b16d7224017fa0b984f75aaff890

### CODE REVIEW

**Comment by whchung** [comment]
@yxsamliu please advise if this PR should be taken prior to #72 .

I'm sorry that for some reason I wasn't notified of PRs against `amd-hcc` in this repository so I reply it so late.

**Comment by yxsamliu** [comment]
We may still need this if we cannot get rid of all the addr space casts. This can be applied after #72 after we solved correctness issue.

**Comment by scchan** [comment]
@yxsamliu do we still need this?

**Comment by yxsamliu** [comment]
It seems we no longer need this since SROA now handles addrspacecast. I will close this for now.

**Pull request closed without merging**
