### PR TITLE
do not traverse callgraph during pass initialization

### PR DESCRIPTION
**Pull request by ssahasra**
The initializer for SelectAcceleratorCode traverses the call-graph to
create a list of functions that are called on the device side. But
this stage is too early, since other passes can change the call-graph
before the pass actually runs.

Hence moving the traversal to runOnModule().

### CODE REVIEW

**Comment by scchan** [comment]
LGTM

**Review by scchan — COMMENTED** [review]
LGTM

**Comment by ssahasra** [comment]
I seem to have the privileges necessary to merge this request myself. Does that mean it's actually okay to do so?

**Comment by scchan** [comment]
@AlexVlx could you review this? thanks

**Review by AlexVlx — APPROVED** [review]
LGTM.

**Pull request merged**
