### PR TITLE
clean up LLVM lit tests for HCC

### PR DESCRIPTION
**Pull request by david-salinas**

### CODE REVIEW

**Review by scchan — CHANGES_REQUESTED** [review]
Does it pass hcc's `make test` because IIRC you mentioned that this change was causing some hcc unit tests to fail?

**Comment by david-salinas** [comment]
It does make the HCC unit tests pass ... I hadn't double checked it before I created this PR.  Let me resolve the issue before we merge this PR.

**Comment by david-salinas** [comment]
OK ... so, I can resolve the HCC unit test failures, but to do so, requires a change to our "lit.cfg" in HCC repo.  So I'll make the change to the lit.cfg in HCC first, and when that PR gets merged, we can merge this PR.

We have some HCC unit tests that rely on pipefail being disabled.  But it would seem that there is at least one LLVM lit test that needs it enabled by default.

**Comment by david-salinas** [comment]
Ok, I've created https://github.com/RadeonOpenCompute/hcc/pull/740 to disable pipefail by default. When this PR gets merged, we can merge this PR.

**Review by scchan — APPROVED** [review]

**Pull request merged**
